# Development environment configuration
server:
  # The HTTP port of the server，The default is 8080
  port: 8080
  servlet:
    # Application access path
    context-path: /
    encoding:
      charset: UTF-8
  tomcat:
    # Uri encoding of Tomcat
    uri-encoding: UTF-8
    threads:
      # The number of threads that Tomcat started to initialize，The default value is 25
      min-spare: 25
      # The maximum number of Tomcat threads is 200 by default
      max: 200

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lobster?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: password
  jpa:
    database: MySQL
    show-sql: true
    generate-ddl: false
    open-in-view: false


springfox:
  documentation:
    swagger-ui:
      enabled: true

logging:
  level:
    org.springframework.security:
      - debug
      - info
    org.springframework.web: error
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

